### ISSUE TITLE
Failure to install Ubuntu Server

### ISSUE THREAD

**Issue by DuckyCrayfish** [raspberrypi/imagewriter#23]
Hello!

Ubuntu Server 18.04.4 LTS fails to install correctly on a Raspberry Pi 2 B v1.1. It fails the validation step and then does not boot.

The Image Writer installs Raspbian correctly on this device, and Ubuntu installs correctly using Etcher.

**Comment by ghollingworth** [comment]
This is a known problem that has been fixed, we're just waiting for a couple of other issues before pushing out a new build

**Comment by ghollingworth** [comment]
Sorry, will leave it open until the build is pushed...

**Comment by DuckyCrayfish** [comment]
Great! Thank you so much

**Comment by ghollingworth** [comment]
Fixed and released, please go to the Raspberry Pi Downloads pages to update

**Comment by lurch** [comment]
Is there any way for a user to tell what version of rpi-imager they're running?

**Comment by maxnet** [comment]
Other then hovering mouse over the .exe (newest version is 1.1 there)
There currently isn't.

**Comment by lurch** [comment]
...which I guess are both Windows-specific?
